name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  coverage_path: Modules/ZetaScheduler.Testing/coverage.xml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:AltCover=true /p:AltCoverCobertura=./coverage.xml /p:AltCoverAssemblyExcludeFilter=Moq|Microsoft|ZetaScheduler.Testing|Altcover|testhost
    - uses: actions/upload-artifact@v4
      with:
        name: drop
        path: ${{ env.coverage_path }}

  coverage_report:
    name: coverage
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Get coverage report
      uses: actions/download-artifact@v4
      with:
        name: drop
        path: ${{ env.coverage_path }}
    - name: Publish coverage results
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ./**/coverage.xml
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
