name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  coverage_path: ./Modules/ZetaScheduler.Testing/coverage.lcov

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:AltCover=true /p:AltCoverLcovReport=./coverage.lcov
    - uses: actions/upload-artifact@v4
      with:
        name: drop
        path: ${{ env.coverage_path }}

  coverage_report:
    name: coverage
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Get coverage report
      uses: actions/download-artifact@v4
      with:
        name: drop
        path: ${{ env.coverage_path }}
    - name: View file tree
      run: tree -d ./
    - name: Report code coverage
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        lcov-file: ${{ env.coverage_path }}
    
